// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpOSj2_qD1iWYvk_W7QmhwPybMw8c2jHg',
    appId: '1:147458789912:web:85e35e863e08aaa5be696d',
    messagingSenderId: '147458789912',
    projectId: 'app-dev-70fc9',
    authDomain: 'app-dev-70fc9.firebaseapp.com',
    databaseURL: 'https://app-dev-70fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-dev-70fc9.firebasestorage.app',
    measurementId: 'G-TVDTTX65B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTQ9CpsXXkiFt9IVfXfTg59vg3HJndXo',
    appId: '1:147458789912:android:47b49c177de17b52be696d',
    messagingSenderId: '147458789912',
    projectId: 'app-dev-70fc9',
    databaseURL: 'https://app-dev-70fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-dev-70fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqeaNsPROO-kjNXgwVskD02ksCbqcFlDA',
    appId: '1:147458789912:ios:9553acd291dab7e2be696d',
    messagingSenderId: '147458789912',
    projectId: 'app-dev-70fc9',
    databaseURL: 'https://app-dev-70fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-dev-70fc9.firebasestorage.app',
    androidClientId: '147458789912-6i89uiljacgrhssi6etva69cjgc6jdhs.apps.googleusercontent.com',
    iosClientId: '147458789912-93ljdl444vp0k1eh2d32utid65s05ta3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqeaNsPROO-kjNXgwVskD02ksCbqcFlDA',
    appId: '1:147458789912:ios:9553acd291dab7e2be696d',
    messagingSenderId: '147458789912',
    projectId: 'app-dev-70fc9',
    databaseURL: 'https://app-dev-70fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-dev-70fc9.firebasestorage.app',
    androidClientId: '147458789912-6i89uiljacgrhssi6etva69cjgc6jdhs.apps.googleusercontent.com',
    iosClientId: '147458789912-93ljdl444vp0k1eh2d32utid65s05ta3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpOSj2_qD1iWYvk_W7QmhwPybMw8c2jHg',
    appId: '1:147458789912:web:1c1f82314c37f115be696d',
    messagingSenderId: '147458789912',
    projectId: 'app-dev-70fc9',
    authDomain: 'app-dev-70fc9.firebaseapp.com',
    databaseURL: 'https://app-dev-70fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-dev-70fc9.firebasestorage.app',
    measurementId: 'G-E8GTRV5K1D',
  );
}
